// Code generated by protoc-gen-go. DO NOT EDIT.
// source: raft.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// You'll likely need to define more specific return codes than these!
type ReturnCode int32

const (
	ReturnCode_SUCCESS ReturnCode = 0
	ReturnCode_FAILURE ReturnCode = 1
)

var ReturnCode_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILURE",
}

var ReturnCode_value = map[string]int32{
	"SUCCESS": 0,
	"FAILURE": 1,
}

func (x ReturnCode) String() string {
	return proto.EnumName(ReturnCode_name, int32(x))
}

func (ReturnCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{0}
}

type AERequest struct {
	Term                 int64    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId             int64    `protobuf:"varint,2,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	PrevLogIndex         int64    `protobuf:"varint,3,opt,name=prevLogIndex,proto3" json:"prevLogIndex,omitempty"`
	PrevLogTerm          int64    `protobuf:"varint,4,opt,name=prevLogTerm,proto3" json:"prevLogTerm,omitempty"`
	Entries              []*Entry `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit         int64    `protobuf:"varint,6,opt,name=leaderCommit,proto3" json:"leaderCommit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AERequest) Reset()         { *m = AERequest{} }
func (m *AERequest) String() string { return proto.CompactTextString(m) }
func (*AERequest) ProtoMessage()    {}
func (*AERequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{0}
}

func (m *AERequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AERequest.Unmarshal(m, b)
}
func (m *AERequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AERequest.Marshal(b, m, deterministic)
}
func (m *AERequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AERequest.Merge(m, src)
}
func (m *AERequest) XXX_Size() int {
	return xxx_messageInfo_AERequest.Size(m)
}
func (m *AERequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AERequest.DiscardUnknown(m)
}

var xxx_messageInfo_AERequest proto.InternalMessageInfo

func (m *AERequest) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AERequest) GetLeaderId() int64 {
	if m != nil {
		return m.LeaderId
	}
	return 0
}

func (m *AERequest) GetPrevLogIndex() int64 {
	if m != nil {
		return m.PrevLogIndex
	}
	return 0
}

func (m *AERequest) GetPrevLogTerm() int64 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AERequest) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *AERequest) GetLeaderCommit() int64 {
	if m != nil {
		return m.LeaderCommit
	}
	return 0
}

type Entry struct {
	Op                   string   `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Val                  string   `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	Term                 int64    `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{1}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetOp() string {
	if m != nil {
		return m.Op
	}
	return ""
}

func (m *Entry) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

func (m *Entry) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

type AEResponse struct {
	Term                 int64    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AEResponse) Reset()         { *m = AEResponse{} }
func (m *AEResponse) String() string { return proto.CompactTextString(m) }
func (*AEResponse) ProtoMessage()    {}
func (*AEResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{2}
}

func (m *AEResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AEResponse.Unmarshal(m, b)
}
func (m *AEResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AEResponse.Marshal(b, m, deterministic)
}
func (m *AEResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AEResponse.Merge(m, src)
}
func (m *AEResponse) XXX_Size() int {
	return xxx_messageInfo_AEResponse.Size(m)
}
func (m *AEResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AEResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AEResponse proto.InternalMessageInfo

func (m *AEResponse) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AEResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterEnum("proto.ReturnCode", ReturnCode_name, ReturnCode_value)
	proto.RegisterType((*AERequest)(nil), "proto.AERequest")
	proto.RegisterType((*Entry)(nil), "proto.Entry")
	proto.RegisterType((*AEResponse)(nil), "proto.AEResponse")
}

func init() { proto.RegisterFile("raft.proto", fileDescriptor_b042552c306ae59b) }

var fileDescriptor_b042552c306ae59b = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcd, 0x6a, 0xeb, 0x30,
	0x10, 0x85, 0xe3, 0x38, 0xbf, 0xe3, 0xdc, 0x8b, 0xab, 0x95, 0xc8, 0xca, 0x78, 0x11, 0x42, 0x17,
	0x59, 0xa4, 0xd0, 0x45, 0xa1, 0x05, 0x63, 0x5c, 0x30, 0x64, 0x25, 0x37, 0x0f, 0xe0, 0xc6, 0x93,
	0x12, 0x88, 0x25, 0x55, 0x92, 0x43, 0xfb, 0x90, 0x7d, 0xa7, 0x62, 0xd9, 0x71, 0x5d, 0xe8, 0x4a,
	0x73, 0xce, 0x48, 0x33, 0xf3, 0x8d, 0x00, 0x54, 0x7e, 0x34, 0x1b, 0xa9, 0x84, 0x11, 0x64, 0x6c,
	0x8f, 0xf0, 0xcb, 0x81, 0x79, 0x94, 0x30, 0x7c, 0xaf, 0x50, 0x1b, 0x42, 0x60, 0x64, 0x50, 0x95,
	0xd4, 0x09, 0x9c, 0xb5, 0xcb, 0x6c, 0x4c, 0x96, 0x30, 0x3b, 0x63, 0x5e, 0xa0, 0x4a, 0x0b, 0x3a,
	0xb4, 0x7e, 0xa7, 0x49, 0x08, 0x0b, 0xa9, 0xf0, 0xb2, 0x13, 0x6f, 0x29, 0x2f, 0xf0, 0x83, 0xba,
	0x36, 0xff, 0xcb, 0x23, 0x01, 0x78, 0xad, 0x7e, 0xa9, 0x4b, 0x8f, 0xec, 0x95, 0xbe, 0x45, 0x56,
	0x30, 0x45, 0x6e, 0xd4, 0x09, 0x35, 0x1d, 0x07, 0xee, 0xda, 0xdb, 0x2e, 0x9a, 0x19, 0x37, 0x09,
	0x37, 0xea, 0x93, 0x5d, 0x93, 0x75, 0xb7, 0xa6, 0x73, 0x2c, 0xca, 0xf2, 0x64, 0xe8, 0xa4, 0xe9,
	0xd6, 0xf7, 0xc2, 0x47, 0x18, 0xdb, 0x57, 0xe4, 0x3f, 0x0c, 0x85, 0xb4, 0x20, 0x73, 0x36, 0x14,
	0x92, 0xf8, 0xe0, 0x5e, 0xf2, 0xb3, 0x25, 0x98, 0xb3, 0x3a, 0xec, 0x60, 0xdd, 0x1f, 0xd8, 0xf0,
	0x01, 0xa0, 0xde, 0x86, 0x96, 0x82, 0x6b, 0xfc, 0x73, 0x1d, 0x14, 0xa6, 0xba, 0x3a, 0x1c, 0x50,
	0x6b, 0x5b, 0x6b, 0xc6, 0xae, 0xf2, 0x76, 0x05, 0xc0, 0xd0, 0x54, 0x8a, 0xc7, 0xa2, 0x40, 0xe2,
	0xc1, 0x34, 0xdb, 0xc7, 0x71, 0x92, 0x65, 0xfe, 0xa0, 0x16, 0xcf, 0x51, 0xba, 0xdb, 0xb3, 0xc4,
	0x77, 0xb6, 0x4f, 0x30, 0x62, 0xf9, 0xd1, 0x90, 0x7b, 0xf8, 0x17, 0x49, 0x89, 0xbc, 0x48, 0x5a,
	0x3e, 0xbf, 0xc5, 0xee, 0xfe, 0x63, 0x79, 0xd3, 0x73, 0x9a, 0x99, 0xc2, 0xc1, 0xeb, 0xc4, 0x7a,
	0x77, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe6, 0xa7, 0x85, 0x09, 0xce, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RaftClient is the client API for Raft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RaftClient interface {
	AppendEntries(ctx context.Context, in *AERequest, opts ...grpc.CallOption) (*AEResponse, error)
}

type raftClient struct {
	cc *grpc.ClientConn
}

func NewRaftClient(cc *grpc.ClientConn) RaftClient {
	return &raftClient{cc}
}

func (c *raftClient) AppendEntries(ctx context.Context, in *AERequest, opts ...grpc.CallOption) (*AEResponse, error) {
	out := new(AEResponse)
	err := c.cc.Invoke(ctx, "/proto.Raft/AppendEntries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftServer is the server API for Raft service.
type RaftServer interface {
	AppendEntries(context.Context, *AERequest) (*AEResponse, error)
}

// UnimplementedRaftServer can be embedded to have forward compatible implementations.
type UnimplementedRaftServer struct {
}

func (*UnimplementedRaftServer) AppendEntries(ctx context.Context, req *AERequest) (*AEResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendEntries not implemented")
}

func RegisterRaftServer(s *grpc.Server, srv RaftServer) {
	s.RegisterService(&_Raft_serviceDesc, srv)
}

func _Raft_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AERequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Raft/AppendEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).AppendEntries(ctx, req.(*AERequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Raft_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Raft",
	HandlerType: (*RaftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendEntries",
			Handler:    _Raft_AppendEntries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raft.proto",
}
